export default {
  
  login: "patelnagendra1",
  id: 55997071,
  node_id: "MDQ6VXNlcjU1OTk3MDcx",
  avatar_url: "https://avatars2.githubusercontent.com/u/55997071?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/patelnagendra1",
  html_url: "https://github.com/patelnagendra1",
  followers_url: "https://api.github.com/users/patelnagendra1/followers",
  following_url: "https://api.github.com/users/patelnagendra1/following{/other_user}",
  gists_url: "https://api.github.com/users/patelnagendra1/gists{/gist_id}",
  starred_url: "https://api.github.com/users/patelnagendra1/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/patelnagendra1/subscriptions",
  organizations_url: "https://api.github.com/users/patelnagendra1/orgs",
  repos_url: "https://api.github.com/users/patelnagendra1/repos",
  events_url: "https://api.github.com/users/patelnagendra1/events{/privacy}",
  received_events_url: "https://api.github.com/users/patelnagendra1/received_events",
  type: "User",
  site_admin: false,
  name: "Nagendra Patel",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 15,
  public_gists: 0,
  followers: 1,
  following: 0,
  created_at: "2019-09-30T17:39:03Z",
  updated_at: "2020-09-28T04:51:13Z"
};
